routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@redirect');
Route::get('docs', 'HomeController@docs')->name('docs');

Route::get('dashboard', 'HomeController@index')->name('home');

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false
]);

Route::get('accounts', 'AccountController@show')->name('accounts.show');
Route::put('accounts', 'AccountController@update')->name('accounts.update');
Route::get('accounts/edit', 'AccountController@edit')->name('accounts.edit');

Route::get('members/export', 'MemberController@export')->name('members.export');
Route::resource('members', 'MemberController');

Route::post('tags/sort', 'TagController@sort');
Route::resource('tags', 'TagController');

Route::patch('faqs/sort', 'FaqController@sort');
Route::resource('faqs', 'FaqController');

Route::resource('news', 'NewsController');

Route::resource('events', 'EventController');

Route::resource('courses', 'CourseController');
Route::post('courses/{course}/members', 'CourseMemberController@store')->name('courses.members');
Route::get('courses/{course}/clone', 'CourseController@clone')->name('courses.clone');

Route::get('courses/{course}/learning-history', 'LearningHistoryController@index')->name('courses.learningHistory');
Route::get('courses/{course}/learning-history/export', 'LearningHistoryController@export')->name('courses.learningHistory.export');

Route::get('lessons', 'LessonController@index');
Route::delete('lessons/{lesson}', 'LessonController@destroy');

Route::name('courseLessons.')->group(function () {
    Route::get('courses/{course}/lessons', 'CourseLessonController@index')->name('index');
    Route::post('courses/{course}/lessons', 'CourseLessonController@store')->name('store');
    Route::get('courses/{course}/lessons/create', 'CourseLessonController@create')->name('create');
    Route::post('courses/{course}/lessons/add', 'CourseLessonController@add')->name('add');
    Route::get('courses/{course}/lessons/{lesson}', 'CourseLessonController@show')->name('show');
    Route::get('courses/{course}/lessons/{lesson}/edit', 'CourseLessonController@edit')->name('edit');
    Route::match(['put', 'patch'], 'courses/{course}/lessons/{lesson}', 'CourseLessonController@update')->name('update');
    Route::delete('courses/{course}/lessons/{lesson}', 'CourseLessonController@destroy')->name('destroy');
});

Route::get('materials', 'MaterialController@index')->name('materials.index');
Route::post('materials', 'MaterialController@store')->name('materials.store');
Route::put('materials/{material}', 'MaterialController@update')->name('materials.update');
Route::delete('materials/{material}', 'MaterialController@destroy')->name('materials.destroy');

// 關於我們
Route::get('about-us', 'AboutUsController@index')->name('about_us.index');
Route::get('about-us/{post}', 'AboutUsController@show')->name('about_us.show');
Route::get('about-us/{post}/edit', 'AboutUsController@edit')->name('about_us.edit');
Route::match(['put', 'patch'],'about-us/{post}', 'AboutUsController@update')->name('about_us.update');

// 申請流程管理
Route::get('applications', 'ApplicationController@index')->name('applications.index');
Route::get('applications/{application}', 'ApplicationController@show')->name('applications.show');
Route::get('applications/{application}/edit', 'ApplicationController@edit')->name('applications.edit');
Route::match(['put', 'patch'],'applications/{application}', 'ApplicationController@update')->name('applications.update');

// 頁面附件管理
Route::post('attachments', 'AttachmentController@store')->name('attachments.store');
Route::match(['put', 'patch'], 'attachments/{attachment}', 'AttachmentController@update')->name('attachment.update');
Route::delete('attachments/{attachment}', 'AttachmentController@destroy')->name('attachments.destroy');

// 聯絡我們管理
Route::get('contacts', 'ContactController@index')->name('contacts.index');
Route::get('contacts/export', 'ContactController@export')->name('contacts.export');
Route::get('contacts/{contact}', 'ContactController@show')->name('contacts.show');
Route::match(['put', 'patch'],'contacts/{contact}', 'ContactController@update')->name('contacts.update');

// 檔案上傳
Route::post('summernote/upload', 'SummernoteUploadController@store');
Route::post('ajax/upload', 'AjaxUploadController@store');

Route::get('variable-settings/{variableSetting}', 'VariableSettingController@get');
Route::post('variable-settings/{variableSetting}', 'VariableSettingController@set');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

//關於
Route::get('history', 'AboutUsController@history')->name('about_us.history');
Route::get('structure', 'AboutUsController@structure')->name('about_us.structure');
Route::get('charter', 'AboutUsController@charter')->name('about_us.charter');

// 最新消息
Route::get('news', 'NewsController@index')->name('news.index');
Route::get('news/{news}', 'NewsController@show')->name('news.show');

// 學術活動
Route::get('events', 'EventController@index')->name('events.index');
Route::get('events/{event}', 'EventController@show')->name('events.show');

//
Route::get('doctors/search', 'DoctorsController@search')->name('doctors.search');

// 申請表頁面
Route::get('specialist-application', 'ApplicationController@specialist')->name('applications.specialist');
Route::get('fellowship-application', 'ApplicationController@fellowship')->name('applications.fellowship');
Route::get('general-application', 'ApplicationController@general')->name('applications.general');

Route::get('faqs', 'FaqController@index')->name('faqs');

Route::get('contact', 'ContactController@show')->name('contact');
Route::post('contact', 'ContactController@store')->name('contact');

app/Http/Controllers/Admin/LearningHistoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use App\Material;
use Box\Spout\Writer\Common\Creator\WriterEntityFactory;
use Illuminate\Http\File;
use Illuminate\Http\Request;

class LearningHistoryController extends Controller
{
    public function index(Course $course)
    {
        $course->load('lessons.materials.members');

        return view('admin.learningHistories.index', compact('course'));
    }

    public function export(Course $course)
    {
        $course->load('lessons.materials.members');

        $writer = WriterEntityFactory::createXLSXWriter();

        $filename = sprintf("%s_上課紀錄_%s.xlsx", $course->title, now()->timestamp);
        $filepath = storage_path("app/tmp/$filename");
        $writer->openToFile($filepath);

        $cells = [
            WriterEntityFactory::createCell('學員名稱'),
            WriterEntityFactory::createCell('學員代號'),
            WriterEntityFactory::createCell('課堂名稱'),
            WriterEntityFactory::createCell('課堂代號'),
            WriterEntityFactory::createCell('教材名稱'),
            WriterEntityFactory::createCell('完成時間'),
        ];

        $singleRow = WriterEntityFactory::createRow($cells);
        $writer->addRow($singleRow);

        $course->lessons->each(function ($lesson) use ($writer, $course) {
            $values = [$lesson->title, $lesson->code];
            $lesson->materials->each(function ($material) use ($writer, $values) {
                array_push($values, $material->name);

                $material->members->each(function ($member) use ($writer, $values) {
                    array_unshift($values, $member->name, $member->code);
                    array_push($values, $member->pivot->completed);

                    $rowFromValues = WriterEntityFactory::createRowFromArray($values);
                    $writer->addRow($rowFromValues);
                });
            });
        });

        $writer->close();

        return response()->file(new File($filepath))
            ->setContentDisposition('attachment', $filename);
    }
}

resources/views/admin/learningHistories/index.blade.php
@extends('layouts.admin')

@section('style')
    <style>
        tr td {
            overflow: hidden;
            text-overflow: ellipsis;
            max-width: 350px;
        }

        .pointer {
            cursor: pointer;
        }
    </style>
@endsection

@section('content')
    {{-- page title --}}
    <div class="page-header">
        <h3 class="page-title"> {{ $course->title }} </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.courses.index') }}">課程管理</a></li>
                <li class="breadcrumb-item"><a href="{{ route('admin.courseLessons.index', $course->id) }}">課堂管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">上課記錄</li>
            </ol>
        </nav>
    </div>
    {{-- content --}}
    <div class="card">
        <div class="card-body">
            <div class="mb-3">
                <a href="{{ route('admin.courses.learningHistory.export', $course->id) }}"
                   class="btn btn-outline-linkedin">匯出上課紀錄</a>
            </div>
            <div>
                <table class="table table-hover mb-3 accordion">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>名稱</th>
                        <th></th>
                    </tr>
                    </thead>
                    @forelse($course->lessons as $key => $lesson)
                        <tr class="pointer"
                            data-toggle="collapse"
                            data-target=".collapse-{{ $lesson->code }}"
                            aria-controls="collapseLesson"
                            aria-expanded="false"
                        >
                            <td>{{ $key + 1 }}</td>
                            <td>{{ $lesson->title }}</td>
                            <td>
                                <button class="btn btn-link btn-sm p-0"><i class="mdi mdi-eye"></i> 檢視記錄</button>
                            </td>
                        </tr>
                        <tr class="collapse collapse-{{ $lesson->code }}">
                            <td class="p-0" colspan="3">
                                <table class="table">
                                    <tr>
                                        <th>姓名</th>
                                        <th>教材</th>
                                        <th>完成時間</th>
                                    </tr>
                                    @foreach($course->members as $member)
                                        @foreach($lesson->materials as $material)
                                            @if($member->isComplete($material))
                                                <tr>
                                                    <td>{{ $member->name }}</td>
                                                    <td>{{ $material->name }}</td>
                                                    <td>{{ $material->members->where('id', $member->id)->first()->pivot->completed }}</td>
                                                </tr>
                                            @endif
                                        @endforeach
                                    @endforeach
                                </table>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="3">沒有課堂資料</td>
                        </tr>
                    @endforelse
                </table>
                <a class="btn btn-light" href="{{ route('admin.courseLessons.index', $course->id) }}">回到課堂管理</a>
            </div>
        </div>
    </div>
@endsection