routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@redirect');
Route::get('docs', 'HomeController@docs')->name('docs');

Route::get('dashboard', 'HomeController@index')->name('home');

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false
]);

Route::get('accounts', 'AccountController@show')->name('accounts.show');
Route::put('accounts', 'AccountController@update')->name('accounts.update');
Route::get('accounts/edit', 'AccountController@edit')->name('accounts.edit');

Route::get('members/export', 'MemberController@export')->name('members.export');
Route::resource('members', 'MemberController');

Route::post('tags/sort', 'TagController@sort');
Route::resource('tags', 'TagController');

Route::patch('faqs/sort', 'FaqController@sort');
Route::resource('faqs', 'FaqController');

Route::resource('news', 'NewsController');

Route::resource('events', 'EventController');

Route::resource('courses', 'CourseController');
Route::post('courses/{course}/members', 'CourseMemberController@store')->name('courses.members');
Route::get('courses/{course}/clone', 'CourseController@clone')->name('courses.clone');

Route::get('courses/{course}/learning-history', 'LearningHistoryController@index')->name('courses.learningHistory');
Route::get('courses/{course}/learning-history/export', 'LearningHistoryController@export')->name('courses.learningHistory.export');

Route::get('lessons', 'LessonController@index');
Route::delete('lessons/{lesson}', 'LessonController@destroy');

Route::name('courseLessons.')->group(function () {
    Route::get('courses/{course}/lessons', 'CourseLessonController@index')->name('index');
    Route::post('courses/{course}/lessons', 'CourseLessonController@store')->name('store');
    Route::get('courses/{course}/lessons/create', 'CourseLessonController@create')->name('create');
    Route::post('courses/{course}/lessons/add', 'CourseLessonController@add')->name('add');
    Route::get('courses/{course}/lessons/{lesson}', 'CourseLessonController@show')->name('show');
    Route::get('courses/{course}/lessons/{lesson}/edit', 'CourseLessonController@edit')->name('edit');
    Route::match(['put', 'patch'], 'courses/{course}/lessons/{lesson}', 'CourseLessonController@update')->name('update');
    Route::delete('courses/{course}/lessons/{lesson}', 'CourseLessonController@destroy')->name('destroy');
});

Route::get('materials', 'MaterialController@index')->name('materials.index');
Route::post('materials', 'MaterialController@store')->name('materials.store');
Route::put('materials/{material}', 'MaterialController@update')->name('materials.update');
Route::delete('materials/{material}', 'MaterialController@destroy')->name('materials.destroy');

// 關於我們
Route::get('about-us', 'AboutUsController@index')->name('about_us.index');
Route::get('about-us/{post}', 'AboutUsController@show')->name('about_us.show');
Route::get('about-us/{post}/edit', 'AboutUsController@edit')->name('about_us.edit');
Route::match(['put', 'patch'],'about-us/{post}', 'AboutUsController@update')->name('about_us.update');

// 申請流程管理
Route::get('applications', 'ApplicationController@index')->name('applications.index');
Route::get('applications/{application}', 'ApplicationController@show')->name('applications.show');
Route::get('applications/{application}/edit', 'ApplicationController@edit')->name('applications.edit');
Route::match(['put', 'patch'],'applications/{application}', 'ApplicationController@update')->name('applications.update');

// 頁面附件管理
Route::post('attachments', 'AttachmentController@store')->name('attachments.store');
Route::match(['put', 'patch'], 'attachments/{attachment}', 'AttachmentController@update')->name('attachment.update');
Route::delete('attachments/{attachment}', 'AttachmentController@destroy')->name('attachments.destroy');

// 聯絡我們管理
Route::get('contacts', 'ContactController@index')->name('contacts.index');
Route::get('contacts/export', 'ContactController@export')->name('contacts.export');
Route::get('contacts/{contact}', 'ContactController@show')->name('contacts.show');
Route::match(['put', 'patch'],'contacts/{contact}', 'ContactController@update')->name('contacts.update');

// 檔案上傳
Route::post('summernote/upload', 'SummernoteUploadController@store');
Route::post('ajax/upload', 'AjaxUploadController@store');

Route::get('variable-settings/{variableSetting}', 'VariableSettingController@get');
Route::post('variable-settings/{variableSetting}', 'VariableSettingController@set');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

//關於
Route::get('history', 'AboutUsController@history')->name('about_us.history');
Route::get('structure', 'AboutUsController@structure')->name('about_us.structure');
Route::get('charter', 'AboutUsController@charter')->name('about_us.charter');

// 最新消息
Route::get('news', 'NewsController@index')->name('news.index');
Route::get('news/{news}', 'NewsController@show')->name('news.show');

// 學術活動
Route::get('events', 'EventController@index')->name('events.index');
Route::get('events/{event}', 'EventController@show')->name('events.show');

//
Route::get('doctors/search', 'DoctorsController@search')->name('doctors.search');

// 申請表頁面
Route::get('specialist-application', 'ApplicationController@specialist')->name('applications.specialist');
Route::get('fellowship-application', 'ApplicationController@fellowship')->name('applications.fellowship');
Route::get('general-application', 'ApplicationController@general')->name('applications.general');

Route::get('faqs', 'FaqController@index')->name('faqs');

Route::get('contact', 'ContactController@show')->name('contact');
Route::post('contact', 'ContactController@store')->name('contact');

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public $timestamps = false;

    protected $fillable = ['name', 'type'];

    public function scopeCourse($query)
    {
        $query->where('type', Course::class);
    }

    public function scopeNews($query)
    {
        $query->where('type', News::class);
    }

    public function scopeContact($query)
    {
        $query->where('type', Contact::class);
    }
}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Contact;
use App\Course;
use App\News;
use App\Tag;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\Rule;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        $tags = Tag::query()->orderBy('weight')->get();
        return view('admin.tags.index', compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $attributes = $this->validate($request, [
            'name' => 'required|max:191',
            'type' => ['required', Rule::in([Course::class, News::class, Contact::class])]
        ], [
            'name.required' => '必須輸入分類標籤名稱',
            'name.max' => '分類標籤名稱不得超過191字',
            'type.required' => '必須選擇類別',
            'type.in' => '類別不在項目中'
        ]);

        Tag::create($attributes);

        return redirect()->route('admin.tags.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Tag $tag
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit', compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Tag $tag
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Validation\ValidationException
     */
    public function update(Request $request, Tag $tag)
    {
        $attributes = $this->validate($request, [
            'name' => 'required|max:191',
        ], [
            'name.required' => '必須輸入分類標籤名稱',
            'name.max' => '分類標籤名稱不得超過191字',
        ]);

        $tag->update($attributes);

        return redirect()->route('admin.tags.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Tag $tag
     * @return \Illuminate\Http\JsonResponse
     * @throws \Exception
     */
    public function destroy(Tag $tag)
    {
        $tag->delete();

        return response()->json('OK');
    }

    public function sort(Request $request)
    {
        DB::beginTransaction();
        collect($request->get('tags'))
            ->each(function ($tagId, $key) {
                Tag::query()
                    ->where('id', $tagId)
                    ->update(['weight' => $key]);
            });
        DB::commit();

        return response()->json('SORTED');
    }
}

resources/views/admin/tags/create.blade.php
@extends('layouts.admin')

@section('style')
    <style>
        .tab-content {
            border-top: 0;
            padding: 2rem 0;
            text-align: justify;
        }
    </style>
@endsection

@section('content')
    {{-- page title --}}
    <div class="page-header">
        <h3 class="page-title"> 建立分類標籤 </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.tags.index') }}">分類標籤管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">編輯分類標籤</li>
            </ol>
        </nav>
    </div>
    {{-- content --}}
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.tags.store') }}" method="post">
                @csrf
                <div class="course-form">
                    <div class="form-group">
                        <label for="name">名稱 <span class="text-danger">*</span></label>
                        <input type="text" id="name" name="name" placeholder="標籤名稱"
                               value="{{ old('name') }}"
                               class="form-control @error('name') is-invalid @enderror"/>
                        @error('name')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <input type="hidden" id="type" name="type" placeholder="類型"
                               class="form-control @error('type') is-invalid @enderror"
                               @switch(request('type'))
                                   @case('news')
                                      @php($type = App\News::class)
                                      @break
                                   @case('course')
                                      @php($type = App\Course::class)
                                      @break
                                   @case('contact')
                                       @php($type = App\Contact::class)
                                       @break
                                   @default
                                      @php($type = '')
                               @endswitch
                                value="{{ $type }}"/>
                        @error('type')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                </div>
                <div>
                    <button type="submit" class="btn btn-gradient-primary mr-2">送出表單</button>
                    <a class="btn btn-light" href="{{ route('admin.tags.index') }}">返回列表</a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/tags/edit.blade.php
@extends('layouts.admin')

@section('style')
    <style>
        .tab-content {
            border-top: 0;
            padding: 2rem 0;
            text-align: justify;
        }
    </style>
@endsection

@section('content')
    {{-- page title --}}
    <div class="page-header">
        <h3 class="page-title"> 編輯分類標籤 </h3>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ route('admin.tags.index') }}">分類標籤管理</a></li>
                <li class="breadcrumb-item active" aria-current="page">編輯分類標籤</li>
            </ol>
        </nav>
    </div>
    {{-- content --}}
    <div class="card">
        <div class="card-body">
            <form action="{{ route('admin.tags.update', $tag->id) }}" method="post">
                @csrf
                @method('PUT')
                <div class="course-form">
                    <div class="form-group">
                        <label for="name">名稱 <span class="text-danger">*</span></label>
                        <input type="text" id="name" name="name" placeholder="標籤名稱"
                               value="{{ old('name', $tag->name) }}"
                               class="form-control @error('name') is-invalid @enderror"/>
                        @error('name')
                        <span class="invalid-feedback" role="alert"><strong>{{ $message }}</strong></span>
                        @enderror
                    </div>
                </div>
                <div class="d-flex justify-content-between">
                    <div>
                        <button type="submit" class="btn btn-gradient-primary mr-2">送出表單</button>
                        <a class="btn btn-light" href="{{ route('admin.tags.index') }}">返回列表</a>
                    </div>
                    <div>
                        <button type="button" data-toggle="modal" data-target="#exampleModal" class="btn btn-danger">刪除分類標籤</button>
                    </div>
                </div>
            </form>

            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel"
                 aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">刪除分類標籤</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            確定要刪除 {{ $tag->name }} ？
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                            <button type="button" onclick="deleteTag()" class="btn btn-inverse-danger">刪除</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        function deleteTag() {
            axios.delete("{{ route('admin.tags.destroy', $tag->id) }}")
                .then(() => {
                    Swal.fire({
                        title: '刪除成功!',
                        text: '',
                        timer: 2000,
                        icon: 'success',
                        confirmButtonText: '確定',
                        onClose: () => {
                            window.location = '{{ route('admin.tags.index') }}'
                        }
                    })
                })
        }
    </script>
@endsection

resources/views/admin/tags/index.blade.php
@extends('layouts.admin')

@section('style')
    <style>
        .tab-content {
            border-top: 0;
            padding: 2rem 0;
            text-align: justify;
        }

    </style>
@endsection

@section('content')
    {{-- page title --}}
    <div class="page-header">
        <h3 class="page-title"> 分類標籤管理 </h3>
        <nav aria-label="breadcrumb">
            <ul class="breadcrumb">
                <li class="breadcrumb-item active" aria-current="page">
                    <span></span>Overview <i class="mdi mdi-alert-circle-outline icon-sm text-primary align-middle"></i>
                </li>
            </ul>
        </nav>
    </div>
    {{-- content --}}
    <div class="card">
        <div class="card-body">
            <ul class="nav nav-tabs" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="news-tab" data-toggle="tab" href="#news" role="tab"
                       aria-controls="news" aria-selected="false">最新消息分類</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="course-tab" data-toggle="tab" href="#course" role="tab"
                       aria-controls="course" aria-selected="true">課程分類</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab"
                       aria-controls="contact" aria-selected="true">聯絡表單分類</a>
                </li>
            </ul>
            <div class="tab-content">
                <div class="tab-pane fade active show" id="news" role="tabpanel" aria-labelledby="news-tab">
                    <div class="mb-3"><a href="{{ route('admin.tags.create', ['type' => 'news']) }}" class="btn btn-outline-linkedin">新增分類</a></div>
                    <tags-sortable-table
                        :list="this.newsTags"
                        v-on:sorted="handleSorting"
                        href="{{ route('admin.tags.create', ['type' => 'news']) }}"
                    ></tags-sortable-table>
                </div>
                <div class="tab-pane fade" id="course" role="tabpanel" aria-labelledby="course-tab">
                    <div class="mb-3"><a href="{{ route('admin.tags.create', ['type' => 'course']) }}" class="btn btn-outline-linkedin">新增分類</a>
                    </div>
                    <tags-sortable-table
                        :list="this.courseTags"
                        v-on:sorted="handleSorting"
                        href="{{ route('admin.tags.create', ['type' => 'course']) }}"
                    ></tags-sortable-table>
                </div>
                <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                    <div class="mb-3"><a href="{{ route('admin.tags.create', ['type' => 'contact']) }}" class="btn btn-outline-linkedin">新增分類</a>
                    </div>
                    <tags-sortable-table
                        :list="this.contactTags"
                        v-on:sorted="handleSorting"
                        href="{{ route('admin.tags.create', ['type' => 'contact']) }}"
                    ></tags-sortable-table>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('script')
    <script>
        app = new Vue({
            "el": "#app",
            data: {
                tags: []
            },
            computed: {
                courseTags() {
                    return this.tags.filter(tag => tag.type === "App\\Course")
                },
                newsTags() {
                    return this.tags.filter(tag => tag.type === "App\\News")
                },
                contactTags() {
                    return this.tags.filter(tag => tag.type === "App\\Contact")
                }
            },
            methods: {
                handleSorting(items) {
                    axios.post('/admin/tags/sort', {
                        tags: items.map(item => item.id)
                    });
                }
            },
            mounted() {
                this.tags = @json($tags)
            }
        });

    </script>


@endsection