routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'HomeController@redirect');
Route::get('docs', 'HomeController@docs')->name('docs');

Route::get('dashboard', 'HomeController@index')->name('home');

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false
]);

Route::get('accounts', 'AccountController@show')->name('accounts.show');
Route::put('accounts', 'AccountController@update')->name('accounts.update');
Route::get('accounts/edit', 'AccountController@edit')->name('accounts.edit');

Route::get('members/export', 'MemberController@export')->name('members.export');
Route::resource('members', 'MemberController');

Route::post('tags/sort', 'TagController@sort');
Route::resource('tags', 'TagController');

Route::patch('faqs/sort', 'FaqController@sort');
Route::resource('faqs', 'FaqController');

Route::resource('news', 'NewsController');

Route::resource('events', 'EventController');

Route::resource('courses', 'CourseController');
Route::post('courses/{course}/members', 'CourseMemberController@store')->name('courses.members');
Route::get('courses/{course}/clone', 'CourseController@clone')->name('courses.clone');

Route::get('courses/{course}/learning-history', 'LearningHistoryController@index')->name('courses.learningHistory');
Route::get('courses/{course}/learning-history/export', 'LearningHistoryController@export')->name('courses.learningHistory.export');

Route::get('lessons', 'LessonController@index');
Route::delete('lessons/{lesson}', 'LessonController@destroy');

Route::name('courseLessons.')->group(function () {
    Route::get('courses/{course}/lessons', 'CourseLessonController@index')->name('index');
    Route::post('courses/{course}/lessons', 'CourseLessonController@store')->name('store');
    Route::get('courses/{course}/lessons/create', 'CourseLessonController@create')->name('create');
    Route::post('courses/{course}/lessons/add', 'CourseLessonController@add')->name('add');
    Route::get('courses/{course}/lessons/{lesson}', 'CourseLessonController@show')->name('show');
    Route::get('courses/{course}/lessons/{lesson}/edit', 'CourseLessonController@edit')->name('edit');
    Route::match(['put', 'patch'], 'courses/{course}/lessons/{lesson}', 'CourseLessonController@update')->name('update');
    Route::delete('courses/{course}/lessons/{lesson}', 'CourseLessonController@destroy')->name('destroy');
});

Route::get('materials', 'MaterialController@index')->name('materials.index');
Route::post('materials', 'MaterialController@store')->name('materials.store');
Route::put('materials/{material}', 'MaterialController@update')->name('materials.update');
Route::delete('materials/{material}', 'MaterialController@destroy')->name('materials.destroy');

// 關於我們
Route::get('about-us', 'AboutUsController@index')->name('about_us.index');
Route::get('about-us/{post}', 'AboutUsController@show')->name('about_us.show');
Route::get('about-us/{post}/edit', 'AboutUsController@edit')->name('about_us.edit');
Route::match(['put', 'patch'],'about-us/{post}', 'AboutUsController@update')->name('about_us.update');

// 申請流程管理
Route::get('applications', 'ApplicationController@index')->name('applications.index');
Route::get('applications/{application}', 'ApplicationController@show')->name('applications.show');
Route::get('applications/{application}/edit', 'ApplicationController@edit')->name('applications.edit');
Route::match(['put', 'patch'],'applications/{application}', 'ApplicationController@update')->name('applications.update');

// 頁面附件管理
Route::post('attachments', 'AttachmentController@store')->name('attachments.store');
Route::match(['put', 'patch'], 'attachments/{attachment}', 'AttachmentController@update')->name('attachment.update');
Route::delete('attachments/{attachment}', 'AttachmentController@destroy')->name('attachments.destroy');

// 聯絡我們管理
Route::get('contacts', 'ContactController@index')->name('contacts.index');
Route::get('contacts/export', 'ContactController@export')->name('contacts.export');
Route::get('contacts/{contact}', 'ContactController@show')->name('contacts.show');
Route::match(['put', 'patch'],'contacts/{contact}', 'ContactController@update')->name('contacts.update');

// 檔案上傳
Route::post('summernote/upload', 'SummernoteUploadController@store');
Route::post('ajax/upload', 'AjaxUploadController@store');

Route::get('variable-settings/{variableSetting}', 'VariableSettingController@get');
Route::post('variable-settings/{variableSetting}', 'VariableSettingController@set');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('index');

//關於
Route::get('history', 'AboutUsController@history')->name('about_us.history');
Route::get('structure', 'AboutUsController@structure')->name('about_us.structure');
Route::get('charter', 'AboutUsController@charter')->name('about_us.charter');

// 最新消息
Route::get('news', 'NewsController@index')->name('news.index');
Route::get('news/{news}', 'NewsController@show')->name('news.show');

// 學術活動
Route::get('events', 'EventController@index')->name('events.index');
Route::get('events/{event}', 'EventController@show')->name('events.show');

//
Route::get('doctors/search', 'DoctorsController@search')->name('doctors.search');

// 申請表頁面
Route::get('specialist-application', 'ApplicationController@specialist')->name('applications.specialist');
Route::get('fellowship-application', 'ApplicationController@fellowship')->name('applications.fellowship');
Route::get('general-application', 'ApplicationController@general')->name('applications.general');

Route::get('faqs', 'FaqController@index')->name('faqs');

Route::get('contact', 'ContactController@show')->name('contact');
Route::post('contact', 'ContactController@store')->name('contact');

app/Http/Controllers/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Course;
use App\Http\Requests\CourseRequest;
use App\Lesson;
use App\Member;
use App\Tag;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\View\View;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        $courses = tap(Course::query(), function ($builder) {
            if ($keyword = request('keyword')) {
                $builder->where('title', 'like', "%$keyword%");
            }
        })->paginate();
        return view('admin.courses.index', compact('courses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        return view('admin.courses.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CourseRequest $request
     * @return JsonResponse|RedirectResponse
     */
    public function store(CourseRequest $request)
    {
        $attributes = $request->validated();

        if ($course = Course::create($attributes)) {
            $course->tags()->sync($request->get('tags'));
        }

        if ($request->isXmlHttpRequest()) {
            return response()->json(['status' => 'OK', 'course' => $course]);
        }

        return redirect()->route('admin.courses.index');
    }

    /**
     * Display the specified resource.
     *
     * @param $course
     * @return JsonResponse|RedirectResponse
     */
    public function show($course)
    {
        $course = Course::findOrNew($course)->load(['members']);

        if (!request()->ajax()) {
            return redirect()->route('admin.courses.edit', $course->id);
        }

        $members = Member::get(['id', 'name', 'code']);
        $tags = Tag::course()->get()->map(function ($news) {
            return ['key' => $news->id, 'value' => $news->name];
        });
        $options = compact('members', 'tags');

        $tags = $course->tags->map(function ($tag) {
            return ['key' => $tag->id, 'value' => $tag->name];
        });

        return response()->json(compact('course', 'tags', 'options'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Course $course
     * @return Application|Factory|Response|View
     */
    public function edit(Course $course)
    {
        return view("admin.courses.edit");
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CourseRequest $request
     * @param Course $course
     * @return JsonResponse|RedirectResponse
     */
    public function update(CourseRequest $request, Course $course)
    {
        $attributes = $request->validated();

        $course->update($attributes);

        $course->tags()->sync($request->get('tags'));

        $course->refresh()->load('members');

        if ($request->ajax()) {
            return response()->json(['status' => 'OK', 'course' => $course]);
        }

        return redirect()->route('admin.courses.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Course $course
     * @return JsonResponse
     * @throws \Exception
     */
    public function destroy(Course $course)
    {
        $course->delete();

        $course->tags()->detach();
        $course->members()->detach();
        $course->lessons()->detach();

        return response()->json("OK");
    }

    public function clone(Course $course)
    {
        $replicateCourse = $course->replicate();

        $replicateLessons = $course->lessons->map(function ($lesson) {
            /** @var Lesson $lesson */
            $replicate = $lesson->replicate();
            $replicate->push();
            $replicate->materials()->sync($lesson->materials);
            return $replicate;
        });

        $replicateCourse->push();

        $replicateCourse->lessons()->saveMany($replicateLessons);

        $replicateCourse->tags()->sync($course->tags);

        return redirect()->route('admin.courses.edit', $replicateCourse->id);
    }
}

app/Http/Controllers/Course/CourseController.php
<?php

namespace App\Http\Controllers\Course;

use App\Course;
use App\Http\Controllers\Controller;
use App\Member;
use Illuminate\Http\Request;

class CourseController extends Controller
{
    public function index()
    {
        $courses = Course::visible()->orderByDesc('start_at')->paginate(12);

        return view('course.index', compact('courses'));
    }

    public function show(Course $course)
    {
        return view('course.show');
    }

    public function api(Course $course)
    {
        $member = auth()->user() ?? resolve(Member::class);

        $course->lessons->each(function ($lesson) use ($member, $course) {
            $lesson->canRead = $member->can('view', [$lesson, $course]);
        });

        return response()->json(compact('course'));
    }

}

app/Http/Controllers/Course/LessonController.php
<?php

namespace App\Http\Controllers\Course;

use App\Course;
use App\Http\Controllers\Controller;
use App\Lesson;

class LessonController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth:web');
    }

    public function show(Course $course, Lesson $lesson)
    {
        $this->authorize('view', [$lesson, $course]);

        return view('course.lesson', compact('course', 'lesson'));
    }

    public function api(Course $course, Lesson $lesson)
    {
        $this->authorize('view', [$lesson, $course]);

        $lesson->materials->each(function ($material) {
            $material->url = route('course.materials.show', $material->id);
        });

        $status = 'OK';

        return response()->json(compact('status', 'course', 'lesson'));
    }

}

app/Http/Controllers/Course/MaterialController.php
<?php

namespace App\Http\Controllers\Course;


use App\Course;
use App\Http\Controllers\Controller;
use App\Material;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\File;

class MaterialController extends Controller
{
    public function show(Material $material)
    {
        $file  = new File(storage_path('app/'. $material->path));

        return response()->file($file);
    }

    public function complete(Course $course, Material $material)
    {
        try {
            $this->authorize('view', [$material, $course]);

            auth()->user()->complete($material);
        } catch (AuthorizationException $exception) {
            return response()->json(['errors' => $exception->getMessage()], 403);
        }
    }
}

app/Http/Controllers/Course/ProfileController.php
<?php

namespace App\Http\Controllers\Course;

use App\Events\ProfileUpdated;
use App\Http\Controllers\Controller;
use App\Member;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class ProfileController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function show()
    {
        $member = auth()->user();
        $courses = $member->courses()->paginate(8);

        return view('course.profile-courses', compact('member', 'courses'));
    }

    public function records()
    {
        $member = auth()->user();
        return view('course.profile-records', compact('member'));
    }

    public function edit()
    {
        $member = auth()->user();
        return view('course.profile-edit', compact('member'));
    }

    public function update(Request $request)
    {
        $attributes = $this->validateRequest($request);

        if ($attributes['password']) {
            Arr::set($attributes, 'password', bcrypt($attributes['password']));
        } else {
            Arr::forget($attributes, 'password');
        }

        $attributes['show_education'] = $request->has('show_education');
        $attributes['show_experience'] = $request->has('show_experience');
        $attributes['show_current_job'] = $request->has('show_current_job');

        /** @var Member $member */
        $member = auth()->user();
        $member->update($attributes);

        event(new ProfileUpdated($member));

        return redirect()->route('course.profile.show');
    }

    public function avatar(Request $request)
    {
        $member = auth()->user();
        $path = sprintf('uploads/avatars/%s', now()->format('Ym'));
        $filePath = $request->file('file')->store($path, ['disk' => 'public']);
        $member->avatar = $filePath;
        $member->save();

        return response()->json(compact('filePath'));
    }

    public function validateRequest(Request $request)
    {
        return $this->validate($request, [
            'name' => 'required|max:191',
            'email.0' => 'required|email|max:191',
            'email.*' => 'nullable|email|max:191',
            'password' => 'nullable|max:191',
            'birth' => 'required|date',
            'gender' => 'in:1,2',
            'phone' => 'required|max:191',
            'mobile' => 'required|max:191',
            'facebook_name' => 'nullable',
            'line_id' => 'nullable',
            'education' => 'nullable',
            'experience' => 'required',
            'clinic_name' => 'required|max:191',
            'clinic_city' => 'required|max:191',
            'clinic_district' => 'required|max:191',
            'clinic_address' => 'required|max:191',
            'certificate_number' => 'max:191'
        ], [
            'name.required' => '請填寫姓名',
            'email.0.required' => '至少填寫一組電子郵件',
            'email.*.email' => '電子郵件的格式不正確',
            'birth.required' => '請填寫生日',
            'birth.date' => '日期格式不正確',
            'gender.in' => '性別不在選項中',
            'phone.required' => '請填寫聯絡電話',
            'mobile.required' => '請填寫手機',
            'facebook_name.max' => '長度不能超過191字',
            'line_id.max' => '長度不能超過191字',
            'experience.required' => '請填寫學 / 經歷資料',
            'clinic_name.required' => '請填寫診所名稱 / 職稱',
            'clinic_city.required' => '請填寫服務城市',
            'clinic_district.required' => '請填寫服務地區',
            'clinic_address.required' => '請填寫診所地址',
            'certificate_number.required' => '請填寫牙醫師證書編號',
        ]);
    }
}

resources/views/course/index.blade.php
@extends('layouts.html')

@section('content')
    <div class="container w-11/12 mx-auto py-8 md:pt-20 md:pb-10">
        <section>
            <div class="text-2xl mb-5 font-bold">所有課程</div>
            <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
                @foreach($courses as $course)
                    @component('course.components.course-card', ['course' => $course])@endcomponent
                @endforeach
            </div>
        </section>
        <div class="pt-8">
            {{ $courses->links() }}
        </div>
    </div>
@endsection

resources/views/course/lesson.blade.php
@extends('layouts.html')

@section('style')
    <style>
        .container {
            min-height: calc(100vh - 140px - 75px);
        }
    </style>
@endsection

@section('content')
    <div class="container w-11/12 mx-auto py-8 md:pt-20 md:pb-10">
        <div v-if="isLoaded">
            <h2 class="text-3xl mb-3">@{{ lesson.title }}</h2>
            <div class="flex flex-col md:flex-row h-32 md:h-auto overflow-scroll md:flex-wrap mb-5">
                <div v-for="material of lesson.materials"
                     @click.prevent="setMaterial(material)"
                     class="lg:w-1/6 md:w-1/4 break-all content-center cursor-pointer hover:bg-gray-300 px-3 py-2 rounded">
                    <span class="flex items-center">
                        <i class="text-2xl md:text-5xl mdi mdi-file-pdf text-red-700" v-if="material.type === 'pdf'"></i>
                        <i class="text-2xl md:text-5xl mdi mdi-youtube text-red-700" v-else-if="material.type === 'video'"></i>
                        <i class="text-2xl md:text-5xl mdi mdi-image-outline text-red-700" v-else-if="material.type === 'image'" ></i> @{{ material.name }}
                    </span>
                </div>
            </div>
            <div class="py-5 flex" v-if="lesson.materials.length !== 0">
                <div class="flex-1" v-if="current.type === 'video'">
                    <video-player v-on:complete="completeMaterial" :material="current"></video-player>
                </div>
                <div class="flex-1" v-show="current.type === 'image'">
                    <img v-if="current.type === 'image'" :src="current.url" alt="" oncontextmenu="return false">
                </div>
                <div class="flex-1" v-show="current.type === 'pdf'" oncontextmenu="return false">
                    <iframe v-if="current.type === 'pdf'" :src="'/pdfjs/web/viewer.html?file=' + current.url" oncontextmenu="return false" style="overflow: auto; width: 100%; min-height: 90vh;"></iframe>
                </div>
            </div>
            <div class="mb-3 flex">
                <span class="text-green-500" style="min-width: 5rem;">教師名稱</span>
                <div>@{{ lesson.teacher }}</div>
            </div>
            <div class="mb-3 flex">
                <span class="text-green-500" style="min-width: 5rem;">教學大綱</span>
                <div class="tracking-widest" v-html="lesson.syllabus"></div>
            </div>
        </div>
        <div class="my-10">
            <a class="cursor-pointer text-green-500 border border-green-500 hover:bg-green-500 hover:text-white px-5 py-2 rounded-full" href="{{ route('course.courses.show', $course->id) }}"> « 回到課程頁 </a>
        </div>
    </div>
@endsection

@section('script')
    <!-- If you'd like to support IE8 (for Video.js versions prior to v7) -->
    <script>
        vueApp = {
            el: '#app',
            data: {
                current: {},
                course: {},
                lesson: {
                    materials: []
                },
                isLoaded: false
            },
            methods: {
                setMaterial(target) {
                    this.current = target;
                    if (target.type !== 'video')
                        this.completeMaterial()
                },
                completeMaterial() {
                    axios.post(`/courses/${this.course.id}/material/${this.current.id}/complete`)
                }
            },
            mounted() {
                let vm = this;
                axios.get('/api' + window.location.pathname)
                    .then(response => {
                        vm.lesson = response.data.lesson
                        vm.course = response.data.course
                        this.setMaterial(vm.lesson.materials[0]);
                    })
                    .finally(() => vm.isLoaded = true);
            }
        };
        const app = new Vue(vueApp);
    </script>
@endsection

resources/views/course/profile-courses.blade.php
@extends('course.profile-layout')

@section('main')
    <section class="pt-8">
        <div class="text-2xl md:text-3xl mb-5 font-bold">我修的課</div>
        <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
            @foreach($courses as $course)
                @component('course.components.course-card', ['course' => $course])
                @endcomponent
            @endforeach
        </div>
    </section>
    @if ($courses->hasPages())
    <div class="pt-8">
        {{ $courses->links() }}
    </div>
    @endif
@endsection

resources/views/course/profile-layout.blade.php
@extends('layouts.html')

@section('style')
    <style>
        .container {
            min-height: calc(100vh - 160px - 66px - 382px);
        }
        .view-profile {
            background-color: #F3F3F3;
            min-height: 382px;
        }
        .tabs {
            top: -41px;
        }

        .tabs a.active {
            background: #F7FAFB;
        }
    </style>
@endsection

@section('content')
    <div class="min-w-full pt-8 pb-24 md:pb-8 view-profile flex flex-col md:flex-row justify-center items-center">
        <div class="avatar rounded-full shadow-sm mb-4 md:mb-0">
                <img class="p-1 border border-gray-400 rounded-md"
                     width="200" alt="{{ $member->name }}的照片"
                     src="{{ $member->avatar ? asset("storage/{$member->avatar}") : asset("images/avatar-elite.jpg") }}"
                >
        </div>
        <div class="flex flex-col md:pl-10">
            <div class="font-bold"><span class="text-3xl">{{ $member->name }}</span><span class="ml-1 text-xl text-gray-700">{{ $member->identity }}</span> </div>
            <div class="text-green-500 mb-4 text-opacity-75">{{ $member->role() }}</div>
            <a class="rounded-full px-10 py-3 bg-green-500 text-white bg-opacity-75 hover:bg-opacity-100" href="{{ route('course.profile.edit') }}">編輯個人檔案</a>
        </div>
    </div>
    <div class="container main mx-auto w-11/12 py-10 relative">
        <div class="absolute tabs">
            <ul class="list-reset flex">
                <li class="-mb-px mr-1">
                    <a class="inline-block py-2 px-4 font-semibold @if('profile' === app('router')->current()->uri) border-l border-t border-r rounded-t active @endif"
                       href="{{ route('course.profile.show') }}">我修的課</a>
                </li>
                <li class="mr-1">
                    <a class="inline-block py-2 px-4 font-semibold @if('profile/records' === app('router')->current()->uri) border-l border-t border-r rounded-t active @endif" href="{{ route('course.profile.records') }}">繳費記錄</a>
                </li>
            </ul>
        </div>
        @if (!$member->is_paid)
            <div class="bg-orange-100 border-l-4 border-orange-500 text-orange-700 p-4" role="alert">
                <p class="font-bold">繳費通知</p>
                <p>本年度{{ now()->format("Y") }}常年會費尚未繳交，請儘速完成會費繳納</p>
            </div>
        @endif
        @yield('main')
    </div>
@endsection

resources/views/course/profile-records.blade.php
@extends('course.profile-layout')

@section('main')
    <section class="pt-8">
        <div class="text-2xl md:text-3xl mb-5 font-bold">繳費記錄</div>
        <table class="table-fixed w-full">
            <tr class="bg-gray-300 text-gray-700">
                <th class="p-2">日期</th>
                <th class="p-2">項目名稱</th>
                <th class="p-2">金額</th>
                <th class="p-2">繳費方式</th>
            </tr>
            @forelse($member->payment_record as $payment)
                <tr class="text-center text-gray-700 hover:bg-gray-300 hover:opacity-75">
                    <td class="p-2">{{ $payment['date'] }}</td>
                    <td class="p-2">{{ $payment['title'] }}</td>
                    <td class="p-2">{{ number_format($payment['amount']) }}</td>
                    <td class="p-2">{{ $payment['method'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4">沒有繳費記錄</td>
                </tr>
            @endforelse
        </table>
    </section>
@endsection

resources/views/course/show.blade.php
@extends('layouts.html')

@section('style')
    <style>

    </style>
@endsection

@section('content')
    <div class="container mx-auto w-11/12 py-8">
        <template v-if="isLoaded">
            <img :src="'/storage/' + course.banner" class="shadow-xl w-full mb-8" alt="課程橫幅" v-if="course.banner != null">
            <img :src="'//place-hold.it/1200x400/cbd5e0/fff/4a5568?text=Banner&fontsize=24'" class="shadow-xl w-full mb-8" alt="課程橫幅" v-else>
            <h2 class="course-title text-4xl mb-4">@{{ course.title }}</h2>
            <div class="course-information mb-12">
                <div class="mb-3 flex">
                    <span class="text-green-500" style="min-width: 5rem;">教師名稱</span>
                    <div>@{{ course.teacher }}</div>
                </div>
                <div class="mb-3 flex">
                    <span class="text-green-500" style="min-width: 5rem;">上課時間</span>
                    <div>@{{ course.start_at }} ~ @{{ course.end_at }}</div>
                </div>
                <div class="mb-3 flex">
                    <span class="text-green-500" style="min-width: 5rem;">上課地點</span>
                    <div>@{{ course.address }}</div>
                </div>
                <div class="mb-3 flex">
                    <span class="text-green-500" style="min-width: 5rem;">報名費用</span>
                    <div>@{{ course.price }}</div>
                </div>
                <div>
                    <div class="text-green-500 mb-3" style="min-width: 5rem;">課程簡介</div>
                    <div class="tracking-widest" v-html="course.summary"></div>
                </div>
            </div>
            <section>
                <div class="text-green-500 mb-3">課程教學</div>
                <table class="table-fixed w-full">
                    <thead>
                    <tr>
                        <th class="px-4 py-2">主題</th>
                        <th class="px-4 py-2">講師</th>
                        <th class="px-4 py-2">上課時間</th>
                    </tr>
                    </thead>

                    <tbody>
                    <tr v-for="lesson of course.lessons">
                        <td class="border px-4 py-2">
                            <a class="text-green-500" :href="`/courses/${course.id}/lessons/${lesson.id}`" v-if="lesson.canRead">@{{ lesson.title }}</a>
                            <span v-else>@{{ lesson.title }}</span>
                        </td>
                        <td class="border px-4 py-2">@{{ lesson.teacher }}</td>
                        <td class="border px-4 py-2">@{{ lesson.start_at }} ~ @{{ lesson.end_at }}</td>
                    </tr>
                    </tbody>
                </table>
            </section>
        </template>
        <div v-else>
            資料載入中 ...
        </div>
    </div>
@endsection

@section('script')
    <script>
        new Vue({
            el: '#app',
            data: {
                course: {},
                isLoaded: false
            },
            mounted() {
                let vm = this;
                axios.get('/api' + window.location.pathname)
                    .then(response => vm.course = response.data.course)
                    .finally(() => vm.isLoaded = true);
            }
        });
    </script>
@endsection